version: '3.4'

services:
  library-webapi:
    image: ${DOCKER_REGISTRY-}gbsodev/gbsodev-techtest-library-webapi:debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 443:443
      - 8081:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - library-database
  library-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=pass@library-database93
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - techtest-dbdata:/var/opt/mssql
    tty: true
volumes:
    techtest-dbdata:

